# Generated by Django 3.0 on 2020-02-03 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('is_main', models.BooleanField(default='false')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 7, 47, 51, 720223)),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time_in_minutes',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.CharField(blank=True, choices=[('LI', 'LITERATURE'), ('FI', 'FILMS'), ('GA', 'GAMES'), ('MU', 'MUSIC'), ('NE', 'NEWS')], default='LI', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='views_amount',
            field=models.IntegerField(default=0),
        ),
    ]
