# Generated by Django 3.0 on 2020-02-03 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200203_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 8, 2, 2, 84719)),
        ),
    ]
