# Generated by Django 3.0 on 2020-02-03 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200203_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reading_time_in_minutes',
            new_name='reading_time',
        ),
        migrations.AddField(
            model_name='article',
            name='starter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 8, 10, 57, 967991)),
        ),
    ]
