# Generated by Django 3.0 on 2020-02-05 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200204_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='brightness',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 10, 25, 37, 700920)),
        ),
    ]
