# Generated by Django 3.0 on 2020-02-10 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200205_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='image_name',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='image_file',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 13, 53, 57, 170281)),
        ),
    ]
