# Generated by Django 3.0 on 2020-02-17 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200210_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='order_in_article',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 12, 14, 15, 451516)),
        ),
    ]
