# Generated by Django 3.0.5 on 2020-04-12 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200412_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 13, 33, 5, 438495)),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
