# Generated by Django 3.0.5 on 2020-04-12 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200412_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 13, 34, 33, 43382)),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='is_main',
            field=models.BooleanField(),
        ),
    ]
